# Generated by Django 6.1.1 on 2026-10-09 06:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


# O catálogo já nasce com nomes simples e as imagens existentes.
PRODUTOS_INICIAIS = [('Feijão carioca', 'Mercearia', 'feijao-kicaldo.png'), ('Feijão preto', 'Mercearia', 'feijao-fugini.png'), ('Leite', 'Laticínios', 'leite-ninho.png'), ('Queijo', 'Laticínios', 'queijo-itambe.png'), ('Iogurte', 'Laticínios', 'iogurte-yopro.png'), ('Flocão de milho', 'Mercearia', 'flocao-bsb.png'), ('Sabão em pó', 'Limpeza', 'sabao-omo.png'), ('Café', 'Mercearia', 'cafe-3coracoes.png'), ('Refrigerante', 'Bebidas', 'coca-cola.png'), ('Detergente', 'Limpeza', 'detergente-ype.png')]


def carregar_catalogo(apps, schema_editor):
    Produto = apps.get_model('produtos', 'Produto')
    for nome, categoria, imagem in PRODUTOS_INICIAIS:
        Produto.objects.using(schema_editor.connection.alias).get_or_create(
            nome=nome, defaults={'categoria': categoria, 'imagem': imagem}
        )


class Migration(migrations.Migration):

    replaces = [('produtos', '0001_initial'), ('produtos', '0002_produto_alter_supermercado_id'), ('produtos', '0003_alter_produto_id_alter_supermercado_id_preco'), ('produtos', '0004_preco_atual'), ('produtos', '0005_supermercado_responsavel'), ('produtos', '0006_produto_imagem_preco_estoque'), ('produtos', '0007_catalogo_inicial'), ('produtos', '0008_produto_foto'), ('produtos', '0009_nomes_simples'), ('produtos', '0010_pedido_itempedido_pedido_pedido_unico_cliente_chave'), ('produtos', '0011_remove_produto_foto')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('imagem', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.UUIDField()),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('em_preparacao', 'Em preparação'), ('concluido', 'Concluído')], default='recebido', max_length=20)),
                ('recebimento', models.CharField(choices=[('delivery', 'Entrega'), ('pickup', 'Retirada')], max_length=10)),
                ('pagamento', models.CharField(choices=[('pix', 'PIX'), ('credito', 'Crédito'), ('debito', 'Débito'), ('entrega', 'Na entrega')], max_length=10)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.CharField(blank=True, max_length=1000)),
                ('cupom', models.CharField(blank=True, max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('taxa_entrega', models.DecimalField(decimal_places=2, max_digits=20)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produtos.pedido')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supermercados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='supermercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='produtos.supermercado'),
        ),
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estoque', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('supermercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.supermercado')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('produto', 'supermercado'), name='preco_unico_produto_supermercado'), models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='preco_valor_positivo')],
            },
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('cliente', 'chave'), name='pedido_unico_cliente_chave'),
        ),
        migrations.RunPython(carregar_catalogo, migrations.RunPython.noop),
    ]
