# Generated by Django 6.1.1 on 2026-10-08 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_supermercado_responsavel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('preco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.preco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_carrinho', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'preco'), name='item_unico_usuario_preco'), models.CheckConstraint(condition=models.Q(('quantidade__gte', 1)), name='item_carrinho_quantidade_positiva')],
            },
        ),
    ]
